In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_excel("📊 Project Retail Sales & Profit Analysis.xlsx")

In [6]:
df.shape

(8399, 21)

In [4]:
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,2012-01-10 00:00:00,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-02-10 00:00:00
2,50,293,2012-01-10 00:00:00,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-03-10 00:00:00
3,80,483,2011-10-07 00:00:00,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-12-07 00:00:00
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   row_id                8399 non-null   int64
 1   order_id              8399 non-null   int64
 2   order_date            8399 non-null   datetime64[ns]
 3   order_priority        8399 non-null   object
 4   order_quantity        8399 non-null   int64
 5   sales                 8399 non-null   float64
 6   discount              8399 non-null   float64
 7   ship_mode             8399 non-null   object
 8   profit                8399 non-null   float64
 9   unit_price            8399 non-null   float64
 10  shipping_cost         8399 non-null   float64
 11  customer_name         8399 non-null   object
 12  province              8399 non-null   object
 13  region                8399 non-null   object
 14  customer_segment      8399 non-null   object
 15  product_category      8399 non-null   object
 16  product_sub-category  8399 non-null   object
 17  product_name          8399 non-null   object
 18  product_container     8399 non-null   object
 19  product_base_margin   8336 non-null   float64
 20  ship_date             8399 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(3), object(10)
memory usage: 1.3+ MB

In [7]:
df.describe()

,Row ID,Order ID,Order Quantity,Sales,Discount,Profit,Unit Price,Shipping Cost,Product Base Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,4200.000000,29965.179783,25.571735,1775.878179,0.049671,181.184424,89.346259,12.838557,0.512513
std,2424.726789,17260.883447,14.481071,3585.050525,0.031823,1196.653371,290.354383,17.264052,0.135589
min,1.000000,3.000000,1.000000,2.240000,0.000000,-14140.700000,0.990000,0.490000,0.350000
25%,2100.500000,15011.500000,13.000000,143.195000,0.020000,-83.315000,6.480000,3.300000,0.380000
50%,4200.000000,29857.000000,26.000000,449.420000,0.050000,-1.500000,20.990000,6.070000,0.520000
75%,6299.500000,44596.000000,38.000000,1709.320000,0.080000,162.750000,85.990000,13.990000,0.590000
max,8399.000000,59973.000000,50.000000,89061.050000,0.250000,27220.690000,6783.020000,164.730000,0.850000

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")

In [9]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'order_priority', 'order_quantity',
       'sales', 'discount', 'ship_mode', 'profit', 'unit_price',
       'shipping_cost', 'customer_name', 'province', 'region',
       'customer_segment', 'product_category', 'product_sub-category',
       'product_name', 'product_container', 'product_base_margin',
       'ship_date'],
      dtype='object')

In [12]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [19]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.isnull().sum()

row_id                  0
order_id                0
order_date              0
order_priority          0
order_quantity          0
sales                   0
discount                0
ship_mode               0
profit                  0
unit_price              0
shipping_cost           0
customer_name           0
province                0
region                  0
customer_segment        0
product_category        0
product_sub-category    0
product_name            0
product_container       0
product_base_margin     0
ship_date               0
dtype: int64

In [20]:
df['product_base_margin'] = df.groupby('product_category')['product_base_margin'].transform(lambda x: x.fillna(x.median()))

In [48]:
df.to_csv("retail_sales_cleaned.csv",index=False)

In [41]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="root",
    password='pass123'
)
print("Connected Successfully!")

Connected Successfully!

In [42]:
cursor = conn.cursor()

# Show all available databases
cursor.execute("SHOW DATABASES")

for db in cursor:
    print(db)

# Select your database
cursor.execute("USE sales")

('ai',)
('crop_price_db',)
('data_analytics',)
('hr_dashboard',)
('information_schema',)
('mysql',)
('performance_schema',)
('prime',)
('sales',)
('smartshop',)

In [43]:
import pymysql

print("PyMySQL Installed Successfully")

PyMySQL Installed Successfully

In [44]:
from sqlalchemy import create_engine

In [45]:
engine = create_engine(
    "mysql+pymysql://root:pass123@127.0.0.1:3306/sales"
)

In [46]:
print(engine)

Engine(mysql+pymysql://root:***@127.0.0.1:3306/sales)

In [47]:
df.to_sql(
    name="retail_sales",
    con=engine,
    if_exists="replace",
    index=False
    
)

8399